"""add book cover columns

Revision ID: ec19854a2035
Revises: 3de5600584c7
Create Date: 2026-06-13 22:25:41.975756

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ec19854a2035'
down_revision: str | Sequence[str] | None = '3de5600584c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_image', sa.LargeBinary(), nullable=True))
    op.add_column('books', sa.Column('cover_content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'cover_content_type')
    op.drop_column('books', 'cover_image')
    # ### end Alembic commands ###
